#!/usr/bin/python

from time import *

print("Mit diesem Programm wird bei der Eingabe bis zur dieser Zahl, alle geraden Zahlen aufgezaehlt.")

x = int(input("\nEingabe bis welche Zahl gerade gezaehlt werden sollte: "))
t1 = clock()

#Zaehlt und sortiert
x = x+2
for i in range (x):
    if i%2 == 1:
        continue
    print(str(i))
print("\nDas sind alle gerade Zahlen.")

#Zeitstopp
t2 = clock()
t = t2-t1
print("%.2fs" % (t))

#Ende
exit = input("\nBitte druecke Enter um das Programm zu beenden.")
